import { Injectable, Logger } from '@nestjs/common';
import { AiProvider, GenerationResult } from './ai-provider.interface';

@Injectable()
export class MockTextProvider implements AiProvider {
  readonly name = 'mock-text';
  private readonly logger = new Logger(MockTextProvider.name);

  async generate(prompt: string): Promise<GenerationResult> {
    this.logger.log('Using mock text provider (Pollinations fallback)');

    // Simulate a small delay
    await new Promise((resolve) => setTimeout(resolve, 500));

    const text = [
      `Here is a thoughtful response to your prompt: "${prompt}"`,
      '',
      'This is a mock response generated by the fallback text provider.',
      'The Pollinations API was unavailable, so this deterministic response was used instead.',
      '',
      `Key points about "${prompt}":`,
      '1. This topic has many interesting aspects to explore.',
      '2. There are various perspectives to consider.',
      '3. Further research could yield deeper insights.',
      '',
      `Generated at: ${new Date().toISOString()}`,
    ].join('\n');

    return { text, provider: this.name };
  }
}
